#!/usr/bin/env bash
# setup-rkhunter-cron-en.sh v0.1
# Create rkhunter daily check (systemd timer) + optional mail alert (English)

set -euo pipefail

### helpers ###

cyan()   { printf '\033[36m%s\033[0m\n' "$*"; }
green()  { printf '\033[32m%s\033[0m\n' "$*"; }
yellow() { printf '\033[33m%s\033[0m\n' "$*"; }
red()    { printf '\033[31m%s\033[0m\n' "$*"; }

info()  { green  "[INFO] $*"; }
warn()  { yellow "[WARN] $*"; }
erro()  { red    "[ERROR] $*"; }

press_enter_to_continue() {
  read -rp "Press Enter to continue ... " _
}

prompt_exit_hint() {
  yellow "You can type Ctrl+C at any time to abort this wizard."
  echo
}

require_root() {
  if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
    erro "Please run this script as root (sudo)!"
    exit 1
  fi
}

step() {
  cyan "======================"
  cyan "$*"
  cyan "======================"
  echo
}

### main ###

step "Step 1/4 - Intro & environment check"
prompt_exit_hint
require_root

if ! command -v rkhunter >/dev/null 2>&1; then
  erro "rkhunter command not found. Please run the rkhunter install script first."
  exit 1
fi

info "rkhunter executable: $(command -v rkhunter)"
echo
press_enter_to_continue

step "Step 2/4 - Choose daily run time"

echo "The check will run once per day using a systemd timer."
echo "Time format: HH:MM (24-hour, server local time)."
echo "Example: 03:15  ->  daily at 03:15 server time."
echo
read -rp "Enter daily run time [HH:MM, default 03:15]: " run_time
run_time="${run_time:-03:15}"

if [[ ! "$run_time" =~ ^([01][0-9]|2[0-3]):[0-5][0-9]$ ]]; then
  erro "Invalid time format: $run_time. Please use HH:MM (24-hour)."
  exit 1
fi

RUN_HH="${run_time%:*}"
RUN_MM="${run_time#*:}"

echo
info "rkhunter check will run daily at ${RUN_HH}:${RUN_MM} (server local time)."
echo "Note: email body will show timestamps in UTC."
echo
press_enter_to_continue

step "Step 3/4 - Mail alerts via send-alert-mail.sh"

ALERT_MODE="silent"
ALERT_SCRIPT="/usr/local/bin/send-alert-mail.sh"

if [[ -x "$ALERT_SCRIPT" ]]; then
  info "Found alert script: $ALERT_SCRIPT"
  read -rp "Enable mail alerts via this script? [Y/n]: " mail_choice
  mail_choice="${mail_choice:-Y}"
  case "$mail_choice" in
    Y|y)
      ALERT_MODE="mail"
      info "Mail alerts will be ENABLED (mode=mail)."
      ;;
    *)
      ALERT_MODE="silent"
      info "Mail alerts will be DISABLED (mode=silent)."
      ;;
  esac
else
  warn "Alert script not found or not executable: $ALERT_SCRIPT"
  warn "The check script will be created in 'silent' mode (no mail)."
  echo
  echo "Hint:"
  echo "  You can later install msmtp + send-alert-mail.sh via hz-oneclick:"
  echo "    -> Mail / SMTP"
  echo "  And then edit /usr/local/bin/rkhunter-check.sh to switch ALERT_MODE=mail."
fi

echo
press_enter_to_continue

step "Step 4/4 - Write check script + systemd service & timer"

CHECK_SCRIPT="/usr/local/bin/rkhunter-check.sh"
SERVICE_FILE="/etc/systemd/system/rkhunter-check.service"
TIMER_FILE="/etc/systemd/system/rkhunter-check.timer"

info "Writing check script: $CHECK_SCRIPT"

cat > "$CHECK_SCRIPT" <<EOF
#!/usr/bin/env bash
# rkhunter-check.sh - auto-generated by hz-oneclick (English)
#
# - Runs: rkhunter --update && rkhunter --check --sk
# - Extracts WARNING / ERROR lines from /var/log/rkhunter.log
# - Optionally sends a mail summary via send-alert-mail.sh
# - Rotates rkhunter.log to avoid unbounded growth
#

set -euo pipefail

ALERT_MODE="${ALERT_MODE}"   # mail / silent
ALERT_SCRIPT="${ALERT_SCRIPT}"
RK_LOG_FILE="/var/log/rkhunter.log"
LOG_MAX_LINES=5000
LOG_KEEP_LINES=3000

HOSTNAME_STR=\$(hostname)
NOW_STR=\$(date -u +"%Y-%m-%d %H:%M:%S UTC")

log()  { echo "[rkhunter-check][\$(date +'%Y-%m-%d %H:%M:%S')] \$*"; }
warn() { echo "[rkhunter-check][WARN][\$(date +'%Y-%m-%d %H:%M:%S')] \$*" >&2; }

run_rkhunter() {
  log "Starting rkhunter --update ..."
  if ! rkhunter --update --quiet; then
    warn "rkhunter --update reported an error. Please review later."
  fi

  log "Starting rkhunter --check --sk ..."
  if ! rkhunter --check --sk --nocolors --quiet; then
    warn "rkhunter --check returned a non-zero exit code (WARNING / ERROR may exist)."
  fi
}

extract_warnings() {
  local new_lines="\${1:-0}"

  if [[ ! -f "\$RK_LOG_FILE" ]]; then
    warn "Log file \$RK_LOG_FILE not found, cannot analyse WARNING / ERROR."
    return 1
  fi

  local base_tail=200
  local tail_lines="\$base_tail"
  if [[ "\$new_lines" -gt 0 ]]; then
    tail_lines="\$new_lines"
  fi

  local tmp_snippet
  tmp_snippet=\$(
    tail -n "\$tail_lines" "\$RK_LOG_FILE" \
      | grep -Ei 'warning|error' \
      | grep -Ev 'Checking if SSH root access is allowed' \
      | grep -Ev 'The SSH and rkhunter configuration options should be the same' \
      | grep -Ev 'Checking /dev for suspicious file types' \
      | grep -Ev 'Suspicious file types found in /dev' \
      | grep -Ev 'Checking for hidden files and directories' \
      | grep -Ev 'Hidden file found: /dev/shm/' \
      || true
  )

  if [[ -z "\$tmp_snippet" ]]; then
    echo ""
    return 0
  fi

  echo "\$tmp_snippet"
  return 0
}

maybe_send_mail() {
  local snippet="\$1"

  if [[ "\$ALERT_MODE" != "mail" ]]; then
    log "Mail alerts disabled (ALERT_MODE=\$ALERT_MODE)."
    return 0
  fi

  if [[ -z "\$snippet" ]]; then
    log "No new WARNING / ERROR detected, no mail will be sent."
    return 0
  fi

  if [[ ! -x "\$ALERT_SCRIPT" ]]; then
    warn "Mail alert mode is 'mail' but ALERT_SCRIPT=\$ALERT_SCRIPT is not executable."
    return 1
  fi

  local subject="[ALERT] rkhunter warnings on \$HOSTNAME_STR"
  local body=""
  body+="rkhunter on host \$HOSTNAME_STR reported WARNING / ERROR.\n"
  body+="Time (UTC): \$NOW_STR\n"
  body+="\n"
  body+="The following lines were extracted from the last 200 lines of \$RK_LOG_FILE:\n"
  body+="----------------------------------------\n"
  body+="\$snippet\n"
  body+="----------------------------------------\n"
  body+="\n"
  body+="Please log into the server and check \$RK_LOG_FILE for full details.\n"

  log "Sending alert mail ..."
  if ! "\$ALERT_SCRIPT" "\$subject" "\$body"; then
    warn "Failed to send mail via \$ALERT_SCRIPT."
    return 1
  fi

  log "Alert mail sent."
}

rotate_log_if_needed() {
  if [[ ! -f "\$RK_LOG_FILE" ]]; then
    return 0
  fi

  local lines
  lines=\$(wc -l < "\$RK_LOG_FILE" 2>/dev/null || echo 0)

  if [[ "\$lines" -gt "\$LOG_MAX_LINES" ]]; then
    log "Log has \$lines lines, above limit \$LOG_MAX_LINES. Truncating ..."
    local tmp_file="\${RK_LOG_FILE}.tmp.\$\$"
    tail -n "\$LOG_KEEP_LINES" "\$RK_LOG_FILE" > "\$tmp_file" 2>/dev/null || true
    mv "\$tmp_file" "\$RK_LOG_FILE"
    log "Log truncated, kept last \$LOG_KEEP_LINES lines."
  fi
}

main() {
  log "===== rkhunter-check START (\$NOW_STR) ====="

  local before_lines=0
  local after_lines=0

  if [[ -f "\$RK_LOG_FILE" ]]; then
    before_lines=\$(wc -l < "\$RK_LOG_FILE" 2>/dev/null || echo 0)
  fi

  run_rkhunter

  if [[ -f "\$RK_LOG_FILE" ]]; then
    after_lines=\$(wc -l < "\$RK_LOG_FILE" 2>/dev/null || echo 0)
  fi

  local new_lines=0
  if (( after_lines > before_lines )); then
    new_lines=\$(( after_lines - before_lines ))
  fi

  local snippet
  snippet=\$(extract_warnings "\$new_lines" || true)

  maybe_send_mail "\$snippet"

  rotate_log_if_needed

  log "===== rkhunter-check END (\$NOW_STR) ====="
}

main "\$@"
EOF

chmod +x "$CHECK_SCRIPT"
info "Check script written and marked executable."

info "Writing service: $SERVICE_FILE"
cat > "$SERVICE_FILE" <<EOF
[Unit]
Description=rkhunter daily check (hz-oneclick)

[Service]
Type=oneshot
ExecStart=$CHECK_SCRIPT
EOF

info "Writing timer: $TIMER_FILE"
cat > "$TIMER_FILE" <<EOF
[Unit]
Description=Run rkhunter-check daily

[Timer]
OnCalendar=*-*-* $RUN_HH:$RUN_MM
Persistent=true
Unit=rkhunter-check.service

[Install]
WantedBy=timers.target
EOF

info "Reloading systemd, enabling and starting timer ..."
systemctl daemon-reload
systemctl enable --now rkhunter-check.timer

echo
green "rkhunter daily check timer has been set up."
echo "  - Time (server local): ${RUN_HH}:${RUN_MM}"
echo "  - Check script: $CHECK_SCRIPT"
echo "  - Timer:       rkhunter-check.timer"
echo "  - Service:     rkhunter-check.service"
echo "  - Mail mode:   $ALERT_MODE"
echo
echo "You can inspect timer status with:"
echo "  systemctl status rkhunter-check.timer --no-pager"
echo
press_enter_to_continue
